export function exportToPDF(title: string, content: string) {
  const win = window.open("", "_blank", "width=800,height=900");
  if (!win) return;
  const safe = content
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  win.document.write(`<!doctype html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>
  body { font: 14px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #111; max-width: 720px; margin: 40px auto; padding: 0 32px; }
  h1 { font-size: 20px; border-bottom: 1px solid #ddd; padding-bottom: 12px; }
  pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
  .meta { color: #666; font-size: 12px; margin-bottom: 24px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #eee; color: #888; font-size: 11px; }
</style></head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by TrudyM AI · ${new Date().toLocaleString()}</div>
  <pre>${safe}</pre>
  <div class="footer">AI-generated content may contain inaccuracies. Review before sharing.</div>
  <script>window.onload = () => { setTimeout(() => window.print(), 200); };</script>
</body></html>`);
  win.document.close();
}
