/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SummarizeRouteImport } from './routes/summarize'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizeRoute = SummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/grammar': typeof GrammarRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/summarize': typeof SummarizeRoute
  '/tasks': typeof TasksRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/grammar': typeof GrammarRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/summarize': typeof SummarizeRoute
  '/tasks': typeof TasksRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/grammar': typeof GrammarRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/summarize': typeof SummarizeRoute
  '/tasks': typeof TasksRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/chat'
    | '/email'
    | '/grammar'
    | '/history'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/research'
    | '/settings'
    | '/summarize'
    | '/tasks'
    | '/api/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/chat'
    | '/email'
    | '/grammar'
    | '/history'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/research'
    | '/settings'
    | '/summarize'
    | '/tasks'
    | '/api/generate'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/chat'
    | '/email'
    | '/grammar'
    | '/history'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/research'
    | '/settings'
    | '/summarize'
    | '/tasks'
    | '/api/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  GrammarRoute: typeof GrammarRoute
  HistoryRoute: typeof HistoryRoute
  NotesRoute: typeof NotesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SummarizeRoute: typeof SummarizeRoute
  TasksRoute: typeof TasksRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarize': {
      id: '/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof SummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  GrammarRoute: GrammarRoute,
  HistoryRoute: HistoryRoute,
  NotesRoute: NotesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SummarizeRoute: SummarizeRoute,
  TasksRoute: TasksRoute,
  ApiGenerateRoute: ApiGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
